apiVersion: v1
kind: Namespace
metadata:
  name: application


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: diplom-app
  name: diplom-app
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diplom-app
  template:
    metadata:
      labels:
        app: diplom-app
    spec:
      containers:
        - image: pugachev72/nginx_custom_01:0.0.4
          imagePullPolicy: IfNotPresent
          name: diplom-app
          resources:
            requests:
              memory: "128Mi"
              cpu: "256m"
            limits:
              memory: "512Mi"
              cpu: "512m"
      terminationGracePeriodSeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: diplom-svc
  namespace: application
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
  selector:
    app: diplom-app
  type: NodePort

