# Версия 3


name: diplom_app_1

on:
  push:
    tags:
      - 'v*'

env:
  IMAGE_TAG: pugachev72/nginx_custom_01
  RELEASE_NAME: nginx-release
  NAMESPACE: application

jobs:
  build-and-push:
    name: Build Docker image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_TAG }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checking version
        run: |
          VERSION=${{ steps.meta.outputs.tags }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#          tags: ${{ env.IMAGE_TAG }}:${{ env.VERSION }}

#  deploy:
#    needs: build-and-push
#    name: Deploy to Kubernetes
#    if: startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/v')
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#      - name: Configure Kubernetes CLI
#        uses: azure/k8s-set-context@v4
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.KUBECONFIG }}
#      - name: Deploy to Kubernetes with Helm
#        run: |
#          helm upgrade --install ${{ env.RELEASE_NAME }} ./nginx_ci --namespace ${{ env.NAMESPACE }} --set image.tag=${{ env.VERSION }}

